title: Assessment
layout: base
theme: minima
description: An actuall assessment program by BFI ITG Software

minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/einra11" }
